services:
  - type: web
    name: ferme-ia-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn agent:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7316577234:AAG1lDOcnJoXuvOaCJvsgWn_-VqzIXtzXLo
      - key: TELEGRAM_CHAT_ID
        value: 6800524671
